export default  {
    body: document.querySelector('body'),
    navItemLinks: document.querySelectorAll('.navigation__list__item-link'),
    svgs: {
        homeAboutLine: document.getElementById("leading-line0"),
        homeProjectLine: document.getElementById("leading-line1"),
        homeTechnologyLine: document.getElementById("leading-line2"),
        homeContactLine: document.getElementById("leading-line3"),
        contactAboutLine: document.getElementById("leading-line-contact0"),
        contactProjectLine: document.getElementById("leading-line-contact1"),
        contactTechnologiesLine: document.getElementById("leading-line-contact2"),
        contactHomeLine: document.getElementById("leading-line-contact4"),
        technologyAboutLine: document.getElementById("leading-line-technology0"),
        technologyContactLine: document.getElementById("leading-line-technology3"),
        technologyProjectLine: document.getElementById("leading-line-technology1"),
        technologyHomeLine: document.getElementById("leading-line-technology4"),
        aboutContactLine: document.getElementById("leading-line-about3"),
        aboutHomeLine: document.getElementById("leading-line-about4"),
        aboutProjectLine: document.getElementById("leading-line-about1"),
        aboutTechnologiesLine: document.getElementById("leading-line-about2"),
        projectAboutLine: document.getElementById("leading-line-project0"),
        projectContactLine: document.getElementById("leading-line-project3"),
        projectHomeLine: document.getElementById("leading-line-project4"),
    },
    pages: {
        contactPage: document.getElementById("contact-page"),
        mainPage: document.getElementById("main-page"),
        aboutPage: document.getElementById("about-page"),
        projectPage: document.getElementById("project-page"),
        technologyPage: document.getElementById("technology-page"),
    },
    links: {
        aboutAboutLink: document.getElementById("about__main-link0"),
        projectProjectLink: document.getElementById("project__main-link1"),
        technologiesTechnologiesLink: document.getElementById("technology__main-link2"),
        homeContactLink: document.getElementById("main-link3"),
        contactContactLink: document.getElementById("contact__main-link3"),
        homeTechnologyLink: document.getElementById("main-link2"),
        homeAboutLink: document.getElementById("main-link0"),
        homeProjectLink: document.getElementById("main-link1"),
    }
}